services:
  neo4j:
    image: neo4j:3.5
    container_name: crimekgqa-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - neo4j_data:/data/databases
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4JLABS_PLUGINS: '["apoc"]'

  app:
    build: .
    container_name: crimekgqa-app
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - VERTEX_PROJECT=crimekgpa
      - VERTEX_LOCATION=us-central1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json
    volumes:
      - ./service-account-key.json:/app/service-account-key.json
    depends_on:
      - neo4j

volumes:
  neo4j_data:
